// ──────────────────────────────────────────────────────────────────────────
// Demo engagements across every SEO type. Powers the top-bar client switcher
// so the whole app can operate as a multi-type SEO Operations Platform —
// one engine, the playbooks/specialists/recommendations change per client.
// ──────────────────────────────────────────────────────────────────────────

import type { Engagement } from "@/components/engagement/store";

export const demoEngagements: Engagement[] = [
  {
    business: "Northwind Heating & Air",
    website: "northwindhvac.com",
    industry: "HVAC / Home Services",
    market: "Austin, TX",
    model: "Local",
    goals: ["More Leads", "More Calls", "More AI Visibility"],
    problems: ["GBP Visibility", "Leads Down", "AI Visibility"],
    assets: ["Google Business Profile", "GA4", "Search Console", "CRM"],
    competitors: ["ATX Comfort Pros", "Lone Star Mechanical", "Hill Country HVAC"],
    confidence: 92,
    scores: { visibility: 48, authority: 41, trust: 57, ai: 29, lead: 52, revenue: 61 },
    clientId: "northwind",
  },
  {
    business: "Trailhead Outfitters",
    website: "trailheadoutfitters.com",
    industry: "Outdoor Gear / Ecommerce",
    market: "Denver, CO",
    model: "Ecommerce",
    goals: ["More Revenue", "Category Rankings", "More Traffic"],
    problems: ["Faceted-nav crawl waste", "Thin collection pages", "Duplicate products"],
    assets: ["GA4", "Search Console", "Shopify", "Merchant Center"],
    competitors: ["REI", "Backcountry", "Moosejaw"],
    confidence: 88,
    scores: { visibility: 52, authority: 55, trust: 60, ai: 30, lead: 48, revenue: 64 },
    clientId: "trailhead",
  },
  {
    business: "Acme Corp",
    website: "acmecorp.com",
    industry: "B2B Software / SaaS",
    market: "San Francisco, CA",
    model: "SaaS",
    goals: ["Pipeline", "Topical Authority", "BOFU Coverage"],
    problems: ["Thin BOFU", "Weak comparison pages", "No programmatic set"],
    assets: ["GA4", "Search Console", "HubSpot"],
    competitors: ["Monday", "Asana", "ClickUp"],
    confidence: 84,
    scores: { visibility: 56, authority: 49, trust: 60, ai: 34, lead: 55, revenue: 61 },
    clientId: "acme",
  },
  {
    business: "Vantage Retail",
    website: "vantageretail.com",
    industry: "Enterprise E-commerce",
    market: "New York, NY",
    model: "Enterprise",
    goals: ["Indexation", "Crawl Efficiency", "Template Performance"],
    problems: ["Crawl-budget waste", "9,200 orphan URLs", "Template decay"],
    assets: ["Search Console", "Adobe Analytics", "Log Files"],
    competitors: ["Wayfair", "Target", "Walmart"],
    confidence: 80,
    scores: { visibility: 53, authority: 58, trust: 62, ai: 27, lead: 49, revenue: 64 },
    clientId: "vantage",
  },
  {
    business: "Helios Media",
    website: "heliosmedia.com",
    industry: "Digital Publisher",
    market: "Chicago, IL",
    model: "Migration",
    goals: ["Preserve Equity", "Zero Traffic Loss", "Clean Redirects"],
    problems: ["Replatforming risk", "Redirect mapping", "Staging parity"],
    assets: ["Search Console", "GA4", "Staging Crawl"],
    competitors: ["Vox", "BuzzFeed", "The Verge"],
    confidence: 76,
    scores: { visibility: 58, authority: 62, trust: 64, ai: 33, lead: 40, revenue: 50 },
    clientId: "helios",
  },
  {
    business: "Lumen Health",
    website: "lumenhealth.com",
    industry: "Healthcare",
    market: "Boston, MA",
    model: "AI Search",
    goals: ["AI Citations", "Entity Clarity", "Answer Presence"],
    problems: ["Absent from AI answers", "Weak entity model", "Thin schema"],
    assets: ["Search Console", "GA4", "Schema"],
    competitors: ["Healthline", "WebMD", "Mayo Clinic"],
    confidence: 79,
    scores: { visibility: 50, authority: 54, trust: 66, ai: 24, lead: 45, revenue: 52 },
    clientId: "lumen",
  },
];
