"use client";

import * as React from "react";
import Link from "next/link";
import {
  AlertTriangle,
  ArrowRight,
  Check,
  CheckCircle2,
  CircleDot,
  Download,
  ExternalLink,
  FileText,
  KeyRound,
  LockKeyhole,
  MessageSquareText,
  RefreshCcw,
  Search,
  ShieldCheck,
  Sparkles,
  Upload,
  XCircle,
} from "lucide-react";
import { GeoGrid } from "@/components/dashboard/geo-grid";
import {
  campaignKpis,
  citations,
  clientRequests as seedRequests,
  contentItems,
  demoCampaigns,
  integrations as seedIntegrations,
  keywordMap,
  latestReviews,
  leadSummaries,
  rankingSummaries,
  reports,
  reviewSummaries,
  tasks,
} from "@/lib/local-growth/demo-data";
import type { ClientRequest, ContentItem, Integration } from "@/lib/local-growth/types";

export function DemoLogin() {
  const [role, setRole] = React.useState("seo_strategist");
  const [workspace, setWorkspace] = React.useState("agency");
  const [signedIn, setSignedIn] = React.useState(false);
  const clientRole = role.startsWith("client_");

  React.useEffect(() => { if (clientRole && workspace === "agency") setWorkspace("capital-comfort"); }, [clientRole, workspace]);

  if (signedIn) {
    const href = clientRole ? `/growth/campaigns/${workspace}` : "/growth";
    return <div className="mx-auto max-w-xl rounded-2xl border border-emerald-200 bg-white p-7 shadow-[var(--shadow-card)]"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><Check className="h-5 w-5" /></div><h1 className="mt-4 text-2xl font-semibold text-slate-950">Demo workspace unlocked</h1><p className="mt-2 text-sm leading-6 text-slate-600">You selected <b>{role.replaceAll("_", " ")}</b>. The production schema enforces tenant access with Supabase RLS; this no-credential demo selector lets the static build exercise role-aware UX.</p><Link href={href} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Enter workspace <ArrowRight className="h-4 w-4" /></Link></div>;
  }

  return <div className="mx-auto max-w-2xl space-y-5"><header className="text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-slate-950 text-emerald-400"><KeyRound className="h-5 w-5" /></div><h1 className="mt-4 text-3xl font-semibold text-slate-950">Local Growth OS</h1><p className="mt-2 text-sm text-slate-600">Role-aware demo login and workspace selector</p></header><div className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-[var(--shadow-card)]"><label className="block"><Label>Role</Label><select value={role} onChange={(e) => setRole(e.target.value)} className={fieldClass}><option value="agency_admin">Agency Admin</option><option value="lead_seo">Lead SEO</option><option value="seo_strategist">SEO Strategist</option><option value="content_outreach">Content / Outreach Specialist</option><option value="client_viewer">Client Viewer</option><option value="client_editor">Client Editor</option></select></label><label className="mt-4 block"><Label>Workspace</Label><select value={workspace} onChange={(e) => setWorkspace(e.target.value)} className={fieldClass}>{!clientRole && <option value="agency">Local Growth Lab · Agency</option>}{demoCampaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.clientName}</option>)}</select></label><div className="mt-4 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-600"><b>Demo accounts:</b> agency-admin@localgrowth.demo, lead-seo@localgrowth.demo, strategist@localgrowth.demo, content@localgrowth.demo, capital-client@localgrowth.demo. Demo password: <code className="rounded bg-white px-1.5 py-0.5">LocalGrowthDemo!</code></div><button onClick={() => setSignedIn(true)} className="mt-5 w-full rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">Continue in demo mode</button></div></div>;
}

export function KeywordMappingScreen() {
  const [query, setQuery] = React.useState("");
  const [campaignId, setCampaignId] = React.useState("all");
  const rows = keywordMap.filter((row) => (campaignId === "all" || row.campaignId === campaignId) && `${row.cluster} ${row.primaryKeyword} ${row.service} ${row.location}`.toLowerCase().includes(query.toLowerCase()));
  const cannibalization = rows.filter((row) => (row.competingUrls?.length ?? 0) > 1);
  const unmapped = rows.filter((row) => !row.targetUrl && row.businessValue >= 4);
  const csv = [["Cluster","Primary keyword","Intent","Volume","CPC","Business value","Target URL"]].concat(rows.map((row) => [row.cluster,row.primaryKeyword,row.intent,String(row.searchVolume),String(row.cpc),String(row.businessValue),row.targetUrl ?? ""])).map((row) => row.map(csvCell).join(",")).join("\n");

  return <Screen title="Keyword & page mapping" eyebrow="Search demand architecture" subtitle="One preferred URL per primary cluster, with cannibalization and unmapped commercial demand surfaced before content production." actions={<><a download="keyword-map.csv" href={`data:text/csv;charset=utf-8,${encodeURIComponent(csv)}`} className={outlineButton}><Download className="h-4 w-4" />CSV</a><button className={darkButton}><Upload className="h-4 w-4" />Import CSV</button></>}>
    <div className="grid gap-3 sm:grid-cols-3"><Stat label="Clusters" value={String(rows.length)} /><Stat label="Cannibalization risks" value={String(cannibalization.length)} tone={cannibalization.length ? "amber" : undefined} /><Stat label="Unmapped high-value" value={String(unmapped.length)} tone={unmapped.length ? "red" : undefined} /></div>
    <div className="rounded-2xl border border-[var(--border)] bg-white shadow-[var(--shadow-card)]"><div className="flex flex-col gap-3 border-b border-[var(--border)] p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search keyword, service, city or cluster" className={`${fieldClass} pl-9`} /></div><select value={campaignId} onChange={(e) => setCampaignId(e.target.value)} className="h-10 rounded-lg border border-[var(--border)] bg-white px-3 text-sm"><option value="all">All campaigns</option>{demoCampaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.clientName}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Cluster / keyword</th><th className="px-4 py-3">Intent</th><th className="px-4 py-3">Market</th><th className="px-4 py-3">Vol.</th><th className="px-4 py-3">CPC</th><th className="px-4 py-3">Value</th><th className="px-4 py-3">Preferred target</th><th className="px-4 py-3">SERP</th></tr></thead><tbody className="divide-y divide-[var(--border)]">{rows.map((row) => <tr key={row.id}><td className="px-4 py-4"><div className="font-semibold text-slate-900">{row.cluster}</div><div className="mt-1 text-xs text-slate-500">{row.primaryKeyword}</div></td><td className="px-4 py-4 text-slate-600">{row.intent.replace("_", " ")}</td><td className="px-4 py-4 text-slate-600">{row.location}</td><td className="px-4 py-4 tabular-nums text-slate-700">{row.searchVolume}</td><td className="px-4 py-4 tabular-nums text-slate-700">${row.cpc}</td><td className="px-4 py-4 font-semibold text-slate-800">{row.businessValue}/5</td><td className="px-4 py-4"><div className={row.targetUrl ? "font-mono text-xs text-emerald-700" : "text-xs font-semibold text-red-700"}>{row.targetUrl ?? "UNMAPPED"}</div>{(row.competingUrls?.length ?? 0) > 1 && <div className="mt-1 text-[11px] font-semibold text-amber-700">{row.competingUrls?.length} competing URLs</div>}</td><td className="px-4 py-4"><div className="flex flex-wrap gap-1">{row.serpFeatures.map((feature) => <span key={feature} className="rounded bg-slate-100 px-1.5 py-1 text-[10px] text-slate-600">{feature}</span>)}</div></td></tr>)}</tbody></table></div></div>
  </Screen>;
}

export function RankingsDashboard() {
  const [campaignId, setCampaignId] = React.useState(rankingSummaries[0].campaignId);
  const ranking = rankingSummaries.find((row) => row.campaignId === campaignId) ?? rankingSummaries[0];
  const campaign = demoCampaigns.find((row) => row.id === campaignId);
  return <Screen title="Local rankings" eyebrow="Geo-grid + organic" subtitle="Track 3-pack visibility, average rank, share of local voice and map-vs-organic performance without hiding the search location behind one average.">
    <div className="flex justify-end"><select value={campaignId} onChange={(e) => setCampaignId(e.target.value)} className="h-10 rounded-lg border border-[var(--border)] bg-white px-3 text-sm">{rankingSummaries.map((row) => <option key={row.campaignId} value={row.campaignId}>{demoCampaigns.find((item) => item.id === row.campaignId)?.clientName}</option>)}</select></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Stat label="3-pack visibility" value={`${ranking.localPackVisibility}%`} /><Stat label="Average local rank" value={ranking.averageRank.toFixed(1)} /><Stat label="Share of local voice" value={`${ranking.shareOfLocalVoice}%`} /><Stat label="Organic rank" value={`#${ranking.organicRank}`} /><Stat label="Movement" value={`${ranking.movement > 0 ? "+" : ""}${ranking.movement}`} tone={ranking.movement >= 0 ? "green" : "red"} /></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_0.85fr]"><Card title={`Geo-grid · ${ranking.keyword}`} subtitle={`${campaign?.market} · mobile · Google local pack`}><GeoGrid grid={ranking.grid} /></Card><Card title="Competitive read" subtitle="Strategist notes belong beside the movement, not in a separate spreadsheet."><div className="space-y-3"><Read label="Strongest area" value="Core service radius and neighborhoods nearest the business centroid." /><Read label="Weakest area" value="Outer grid cells where review/entity strength and local relevance fall off." /><Read label="Primary competitor" value={ranking.competitor} /><Read label="Map vs organic" value={`Local avg rank ${ranking.averageRank}; organic rank #${ranking.organicRank}. Treat them as related but separate result systems.`} /></div><textarea rows={4} className="mt-4 w-full rounded-lg border border-[var(--border)] p-3 text-sm" defaultValue="Note ranking movement after material GBP, content, review, citation or competitor changes. Do not assign causation without evidence." /></Card></div>
  </Screen>;
}

export function CitationsScreen() {
  const [filter, setFilter] = React.useState<"all" | "incorrect" | "duplicate" | "claimed">("all");
  const rows = citations.filter((row) => filter === "all" || row.listingStatus === filter);
  const accuracy = citations.length ? Math.round(citations.reduce((sum, row) => sum + row.napMatchScore, 0) / citations.length) : 0;
  return <Screen title="Citations & NAP" eyebrow="Entity consistency" subtitle="The NAP master is the source of truth. Priority listing mismatches and duplicate risk stay visible until verified and corrected." actions={<button className={outlineButton}><Download className="h-4 w-4" />Export CSV</button>}>
    <div className="grid gap-3 sm:grid-cols-4"><Stat label="Accuracy score" value={`${accuracy}%`} tone={accuracy < 90 ? "amber" : "green"} /><Stat label="Incorrect listings" value={String(citations.filter((row) => row.listingStatus === "incorrect").length)} tone="amber" /><Stat label="Duplicate risk" value={String(citations.filter((row) => row.duplicateRisk === "high" || row.duplicateRisk === "critical").length)} /><Stat label="Claimed" value={String(citations.filter((row) => row.listingStatus === "claimed").length)} tone="green" /></div>
    <Card title="NAP master" subtitle="Sensitive public-profile changes should create a client-approval request before execution."><div className="grid gap-3 sm:grid-cols-3"><Read label="Business name" value="Campaign-specific verified legal/public brand record" /><Read label="Address / service area" value="Verified business profile record" /><Read label="Phone" value="Campaign-specific permanent public number" /></div></Card>
    <div className="flex flex-wrap gap-2">{(["all","incorrect","duplicate","claimed"] as const).map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${filter === item ? "bg-slate-950 text-white" : "bg-white text-slate-600 ring-1 ring-[var(--border)]"}`}>{item}</button>)}</div>
    <div className="overflow-x-auto rounded-2xl border border-[var(--border)] bg-white shadow-[var(--shadow-card)]"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Directory</th><th className="px-4 py-3">Campaign</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">NAP match</th><th className="px-4 py-3">Observed phone</th><th className="px-4 py-3">Master phone</th><th className="px-4 py-3">Duplicate risk</th><th className="px-4 py-3">Next action</th></tr></thead><tbody className="divide-y divide-[var(--border)]">{rows.map((row) => <tr key={row.id}><td className="px-4 py-4 font-semibold text-slate-900">{row.directory}</td><td className="px-4 py-4 text-slate-600">{demoCampaigns.find((item) => item.id === row.campaignId)?.clientName}</td><td className="px-4 py-4"><StatusBadge value={row.listingStatus} /></td><td className="px-4 py-4 font-semibold text-slate-800">{row.napMatchScore}%</td><td className={row.phone === row.expectedPhone ? "px-4 py-4 text-slate-600" : "px-4 py-4 font-semibold text-amber-700"}>{row.phone}</td><td className="px-4 py-4 text-slate-600">{row.expectedPhone}</td><td className="px-4 py-4 text-slate-600">{row.duplicateRisk}</td><td className="px-4 py-4 text-slate-600">{row.nextAction}</td></tr>)}</tbody></table></div>
  </Screen>;
}

export function ContentCalendarScreen() {
  return <Screen title="Content pipeline" eyebrow="Local proof + conversion" subtitle="Service pages, location pages, case studies and cost content are tied to real business facts, mapped demand and client asset dependencies." actions={<button className={darkButton}><Sparkles className="h-4 w-4" />New content brief</button>}>
    <div className="grid gap-3 sm:grid-cols-4"><Stat label="Active items" value={String(contentItems.filter((item) => item.status !== "published").length)} /><Stat label="Waiting on client" value={String(contentItems.filter((item) => item.status === "waiting_on_client").length)} tone="amber" /><Stat label="QA flags" value={String(contentItems.reduce((sum, item) => sum + item.qaFlags.length, 0))} tone="amber" /><Stat label="Published" value={String(contentItems.filter((item) => item.status === "published").length)} tone="green" /></div>
    <div className="grid gap-4 xl:grid-cols-3">{contentItems.map((item) => <ContentCard key={item.id} item={item} />)}</div>
    <Card title="Content QA guardrails" subtitle="Local pages should earn their existence with actual market/service value."><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{["Thin location page","Unsupported claims","Repetitive city swapping","Missing real-world proof","Missing CTA","Missing internal links","Missing schema consideration"].map((flag) => <div key={flag} className="flex items-center gap-2 rounded-lg bg-slate-50 p-3 text-sm text-slate-700"><CircleDot className="h-3.5 w-3.5 text-amber-600" />{flag}</div>)}</div></Card>
  </Screen>;
}

export function ContentBriefDetail({ itemId }: { itemId: string }) {
  const item = contentItems.find((row) => row.id === itemId) ?? contentItems[0];
  const campaign = demoCampaigns.find((row) => row.id === item.campaignId);
  return <Screen title={item.title} eyebrow="Content brief" subtitle={`${campaign?.clientName} · ${item.service} · ${item.location}`} actions={<><button className={outlineButton}>Request client assets</button><button className={darkButton}>Approve brief</button></>}>
    <div className="grid gap-5 xl:grid-cols-[1fr_320px]"><div className="space-y-5"><Card title="Search & conversion brief"><div className="grid gap-4 sm:grid-cols-2"><Read label="Intent" value={item.intent} /><Read label="Target URL" value={item.targetUrl} /><Read label="Primary CTA" value={item.type === "project_case_study" ? "Request a project-specific inspection" : "Request an estimate"} /><Read label="Status" value={item.status.replaceAll("_", " ")} /></div></Card><Card title="Business facts + proof"><textarea rows={6} className="w-full rounded-lg border border-[var(--border)] p-3 text-sm" defaultValue="Use only supplied campaign facts, verified service details, approved trust signals and real project evidence. Do not invent credentials, pricing, project details or service areas." /></Card><Card title="Outline"><ol className="space-y-2 text-sm text-slate-700"><li>1. Service + market problem framing</li><li>2. What the service actually includes</li><li>3. When repair vs replacement applies</li><li>4. Real project/process proof</li><li>5. Cost / financing facts only if supplied</li><li>6. FAQs from actual customer objections</li><li>7. Strong conversion CTA</li></ol></Card></div><aside className="space-y-4"><Card title="Client assets required">{item.clientAssetsRequired.length ? <ul className="space-y-2 text-sm text-slate-700">{item.clientAssetsRequired.map((asset) => <li key={asset} className="flex gap-2"><Upload className="mt-0.5 h-4 w-4 text-slate-400" />{asset}</li>)}</ul> : <p className="text-sm text-slate-500">No client assets currently required.</p>}</Card><Card title="QA flags">{item.qaFlags.length ? <ul className="space-y-2">{item.qaFlags.map((flag) => <li key={flag} className="rounded-lg bg-amber-50 p-2.5 text-xs font-medium text-amber-900">{flag}</li>)}</ul> : <div className="flex items-center gap-2 text-sm font-semibold text-emerald-700"><CheckCircle2 className="h-4 w-4" />No current QA flags</div>}</Card><div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-xs leading-5 text-blue-900"><b>AI draft rule:</b> source data must be shown, assumptions labeled, and a human must approve the brief before client-facing use.</div></aside></div>
  </Screen>;
}

export function ReportsScreen() {
  const [campaignId, setCampaignId] = React.useState(reports[0].campaignId);
  const [view, setView] = React.useState<"plain" | "internal">("plain");
  const [status, setStatus] = React.useState(reports[0].publishStatus);
  const report = reports.find((row) => row.campaignId === campaignId) ?? reports[0];
  const campaign = demoCampaigns.find((row) => row.id === campaignId);
  React.useEffect(() => setStatus(report.publishStatus), [report.publishStatus]);
  return <Screen title="Monthly report builder" eyebrow="Client reporting" subtitle="Reports publish from a frozen snapshot so a client never opens last month’s report and sees today’s moving numbers." actions={<button onClick={() => window.print()} className={outlineButton}><FileText className="h-4 w-4" />Print / PDF</button>}>
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[var(--border)] bg-white p-4"><div className="flex flex-wrap gap-2"><select value={campaignId} onChange={(e) => setCampaignId(e.target.value)} className="h-10 rounded-lg border border-[var(--border)] px-3 text-sm">{reports.map((row) => <option key={row.id} value={row.campaignId}>{demoCampaigns.find((item) => item.id === row.campaignId)?.clientName}</option>)}</select><button onClick={() => setView("plain")} className={view === "plain" ? darkButton : outlineButton}>Plain English</button><button onClick={() => setView("internal")} className={view === "internal" ? darkButton : outlineButton}>Internal detail</button></div><div className="flex items-center gap-2"><span className="text-xs text-slate-500">Lead SEO: {report.leadSeoApproval}</span><button disabled={report.leadSeoApproval !== "approved"} onClick={() => setStatus("published")} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white disabled:bg-slate-300">Publish client report</button></div></div>
    <article className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-[var(--shadow-card)] print:border-0 print:shadow-none"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="text-xs font-semibold uppercase tracking-wide text-emerald-700">{report.period}</div><h2 className="mt-1 text-2xl font-semibold text-slate-950">{campaign?.clientName} · Local SEO report</h2></div><StatusBadge value={status} /></div><section className="mt-6"><h3 className="text-sm font-semibold uppercase tracking-wide text-slate-500">Executive summary</h3><p className="mt-2 max-w-4xl text-base leading-7 text-slate-800">{report.executiveSummary}</p></section><div className="mt-6 grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{Object.entries(report.snapshot).map(([key,value]) => <Stat key={key} label={humanize(key)} value={value == null ? "Unavailable" : String(value)} tone={value == null ? "amber" : undefined} />)}</div><div className="mt-6 grid gap-5 lg:grid-cols-3"><ReportList title="Work completed" rows={report.workCompleted} tone="green" /><ReportList title="Risks / blockers" rows={report.risks} tone="amber" /><ReportList title="Next 30 days" rows={report.nextPriorities} tone="blue" /></div>{view === "internal" && <div className="mt-6 rounded-xl bg-slate-950 p-5 text-white"><div className="text-xs font-semibold uppercase tracking-wide text-emerald-400">Internal strategist layer</div><p className="mt-2 text-sm leading-6 text-white/70">Client-facing copy is separate from operational notes, attribution caveats, unresolved hypotheses and production dependencies. This panel never renders in the plain client portal view.</p></div>}<div className="mt-6 border-t border-[var(--border)] pt-4"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">Data freshness</div><div className="mt-2 flex flex-wrap gap-2">{report.freshness.map((item) => <span key={item.source} className={`rounded-full px-2.5 py-1 text-xs font-semibold ${item.status === "fresh" ? "bg-emerald-50 text-emerald-700" : item.status === "stale" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600"}`}>{item.source}: {item.updatedAt ?? item.status}</span>)}</div></div></article>
    <div className="text-sm text-slate-500">Client portal preview: <Link href={`/growth/reports/client/${report.id}`} className="font-semibold text-emerald-700">open published-style report view →</Link></div>
  </Screen>;
}

export function ClientReportView({ reportId }: { reportId: string }) {
  const report = reports.find((row) => row.id === reportId) ?? reports[0];
  const campaign = demoCampaigns.find((row) => row.id === report.campaignId);
  return <div className="mx-auto max-w-5xl space-y-5"><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><div className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4" />Client portal view</div><p className="mt-1 text-emerald-800">Only published/client-visible sections belong here. Internal notes and unapproved AI drafts are excluded.</p></div><article className="rounded-2xl border border-[var(--border)] bg-white p-7 shadow-[var(--shadow-card)]"><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">{report.period}</p><h1 className="mt-1 text-3xl font-semibold text-slate-950">{campaign?.clientName}</h1><p className="mt-1 text-sm text-slate-500">Local search progress report</p><p className="mt-6 text-lg leading-8 text-slate-800">{report.executiveSummary}</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{Object.entries(report.snapshot).slice(0,6).map(([key,value]) => <Stat key={key} label={humanize(key)} value={value == null ? "Unavailable" : String(value)} />)}</div><div className="mt-6 grid gap-5 md:grid-cols-3"><ReportList title="What we completed" rows={report.workCompleted} tone="green" /><ReportList title="What needs attention" rows={report.risks} tone="amber" /><ReportList title="What we’re doing next" rows={report.nextPriorities} tone="blue" /></div></article></div>;
}

export function ClientRequestsPortal() {
  const [rows, setRows] = React.useState(seedRequests);
  const [mode, setMode] = React.useState<"agency" | "client">("agency");
  function update(id: string, status: ClientRequest["status"]) { setRows((current) => current.map((row) => row.id === id ? { ...row, status } : row)); }
  return <Screen title="Client requests" eyebrow={mode === "agency" ? "Agency request queue" : "Client portal"} subtitle="Requests explain exactly what is needed and why it matters, in language a contractor owner can act on." actions={<div className="flex rounded-lg border border-[var(--border)] bg-white p-1"><button onClick={() => setMode("agency")} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${mode === "agency" ? "bg-slate-950 text-white" : "text-slate-600"}`}>Agency view</button><button onClick={() => setMode("client")} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${mode === "client" ? "bg-slate-950 text-white" : "text-slate-600"}`}>Client view</button></div>}>
    <div className="grid gap-4 xl:grid-cols-2">{rows.map((request) => { const campaign = demoCampaigns.find((row) => row.id === request.campaignId); return <article key={request.id} className="rounded-2xl border border-[var(--border)] bg-white p-5 shadow-[var(--shadow-card)]"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{campaign?.clientName} · {request.type.replaceAll("_", " ")}</div><h2 className="mt-1 text-base font-semibold text-slate-950">{request.title}</h2></div><StatusBadge value={request.status} /></div><div className="mt-4 rounded-xl bg-blue-50 p-3"><div className="text-[10px] font-semibold uppercase tracking-wide text-blue-700">Why it matters</div><p className="mt-1 text-sm leading-5 text-blue-900">{request.whyItMatters}</p></div><div className="mt-4"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">Exact requested item</div><p className="mt-1 text-sm leading-6 text-slate-700">{request.exactRequestedItem}</p></div><div className="mt-4 flex flex-wrap items-center justify-between gap-2 text-xs text-slate-500"><span>Due {request.dueDate} · {request.contact}</span>{request.relatedContent && <span>Related: {request.relatedContent}</span>}</div>{mode === "client" && <div className="mt-4 space-y-3 border-t border-[var(--border)] pt-4"><textarea rows={3} placeholder="Add a comment or answer" className="w-full rounded-lg border border-[var(--border)] p-3 text-sm" /><div className="flex flex-wrap gap-2"><button className={outlineButton}><Upload className="h-4 w-4" />Upload files</button><button onClick={() => update(request.id,"approved")} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Approve / supplied</button><button onClick={() => update(request.id,"rejected")} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Reject</button><button onClick={() => update(request.id,"unavailable")} className="rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-semibold text-slate-600">Unavailable</button></div></div>}</article>; })}</div>
  </Screen>;
}

export function IntegrationsScreen() {
  const [rows, setRows] = React.useState(seedIntegrations);
  const [refreshing, setRefreshing] = React.useState<string | null>(null);
  function refresh(provider: string) { setRefreshing(provider); window.setTimeout(() => { setRows((current) => current.map((row) => row.provider === provider ? { ...row, lastSync: "just now" } : row)); setRefreshing(null); }, 500); }
  return <Screen title="Integrations" eyebrow="Connector architecture" subtitle="Each source has connection state, sync history, freshness, errors and a CSV/manual fallback. Mock providers keep the OS fully usable before OAuth is configured.">
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map((row) => <article key={row.provider} className="rounded-2xl border border-[var(--border)] bg-white p-5 shadow-[var(--shadow-card)]"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold uppercase tracking-wide text-slate-400">{row.category}</div><h2 className="mt-1 font-semibold text-slate-950">{row.label}</h2></div><StatusBadge value={row.state} /></div><p className="mt-3 min-h-10 text-xs leading-5 text-slate-500">{row.detail}</p><div className="mt-4 grid grid-cols-2 gap-2"><Read label="Mode" value={row.mode} /><Read label="Fresh" value={row.dataFreshAt ?? "Unavailable"} /></div><div className="mt-4 flex items-center justify-between border-t border-[var(--border)] pt-3"><span className="text-[11px] text-slate-400">Last sync: {row.lastSync ?? "Never"}</span><button onClick={() => refresh(row.provider)} disabled={refreshing === row.provider || row.state === "blocked"} className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-700 disabled:text-slate-300"><RefreshCcw className={`h-3.5 w-3.5 ${refreshing === row.provider ? "animate-spin" : ""}`} />Refresh</button></div></article>)}</div>
    <Card title="Adapter contract" subtitle="Live providers replace mock providers behind the same campaign data interfaces."><pre className="overflow-x-auto rounded-xl bg-slate-950 p-4 text-xs leading-6 text-slate-200">{`interface Connector<T> {\n  provider: string;\n  connect(): Promise<ConnectionState>;\n  sync(context: CampaignContext): Promise<SyncResult<T>>;\n  freshness(): Promise<DataFreshness>;\n  importCsv?(rows: unknown[]): Promise<SyncResult<T>>;\n}`}</pre></Card>
  </Screen>;
}

export function GbpScreen() { return <SimpleDataModule title="Google Business Profile" eyebrow="GBP operations" summary="Categories, services, links, UTM, hours, photos, reviews, Q&A, posts, attributes and policy risk all roll up to the same campaign record." cards={[{label:"Policy",value:"No keyword-stuffed names, fake locations, duplicate profiles or review manipulation"},{label:"Access",value:"Capital Comfort: requested · DMV Roofing: connected · Potomac Plumbing: connected"},{label:"High-risk changes",value:"Strategist acknowledgement required before ready/publish"}]} links={[['Open GBP audit','/growth/audits/gbp'],['Open reviews','/growth/reviews']]} />; }
export function ReviewsScreen() { return <SimpleDataModule title="Reviews & reputation" eyebrow="Trust operations" summary="Review count, rating, response queue and velocity are tracked without fake reviews, gating or policy-breaking incentives." cards={reviewSummaries.map((row) => ({label:demoCampaigns.find((item) => item.id===row.campaignId)?.clientName ?? row.campaignId,value:`${row.count} reviews · ${row.rating}★ · ${row.monthlyVelocity}/mo · ${row.responseRate}% responded`}))} links={[['Open client requests','/growth/requests']]} extra={<div className="grid gap-3 md:grid-cols-3">{latestReviews.map((review) => <div key={`${review.campaignId}-${review.reviewer}`} className="rounded-xl border border-[var(--border)] bg-white p-4"><div className="flex justify-between"><b className="text-sm text-slate-800">{review.reviewer}</b><span className="text-xs text-amber-700">{review.rating}★</span></div><p className="mt-2 text-xs leading-5 text-slate-600">{review.text}</p><div className="mt-2 text-[11px] text-slate-400">{review.status}</div></div>)}</div>} />; }
export function CompetitorsScreen() { return <SimpleDataModule title="Competitor intelligence" eyebrow="Gap analysis" summary="Compare GBP, reviews, service pages, local content, links, citations, conversion UX and ranking strength, then turn a real gap into an initiative or task." cards={[{label:"Capital Comfort",value:"District Air Pros leads review velocity and outer-grid trust"},{label:"DMV Roofing",value:"Maryland Roof Masters leads storm-content depth and review velocity"},{label:"Potomac Plumbing",value:"Old Town Plumbing leads click-to-call UX and category breadth"}]} links={[['Create roadmap opportunity','/growth/roadmap'],['Open rankings','/growth/rankings']]} />; }
export function TechnicalScreen() { return <SimpleDataModule title="Technical SEO" eyebrow="Site health" summary="Indexing, crawlability, redirects, canonicals, sitemaps, robots, CWV, mobile UX, broken links, structured data and rendering stay in a validation-driven issue queue." cards={[{label:"Schema rule",value:"Schema must match visible content; rich-result eligibility is never guaranteed"},{label:"Potomac Plumbing",value:"Water-heater page internal-link issue · planned"},{label:"Validation",value:"Resolved sitemap redirect chain · validated Aug 29"}]} links={[['Open audits','/growth/audits'],['Open tasks','/growth/tasks']]} />; }
export function OutreachScreen() { return <SimpleDataModule title="Links & outreach" eyebrow="Local authority" summary="Local sponsorships, associations, suppliers, earned mentions and competitive link gaps are tracked as opportunities—not as a generic backlink count." cards={[{label:"Opportunity types",value:"Local sponsorship · association · supplier · PR mention · resource inclusion"},{label:"Evidence",value:"Source URL, contact, rationale, status and target URL"},{label:"Guardrail",value:"No invented placements or fabricated outreach outcomes"}]} links={[['Open competitors','/growth/competitors'],['Open roadmap','/growth/roadmap']]} />; }
export function LeadsScreen() { return <SimpleDataModule title="Leads & conversions" eyebrow="Business outcomes" summary="Lead → qualified → booked → closed is separated from traffic metrics. Revenue stays blank unless a real source explicitly provides it." cards={leadSummaries.map((row) => ({label:demoCampaigns.find((item)=>item.id===row.campaignId)?.clientName ?? row.campaignId,value:`${row.leads} leads · ${row.qualified} qualified · ${row.booked} booked · ${row.closed} closed${row.revenueSourceAvailable ? ` · $${row.revenue?.toLocaleString()} verified revenue` : ' · revenue unavailable'}`}))} links={[['Open campaign dashboards','/growth/campaigns'],['Open reports','/growth/reports']]} />; }
export function TemplatesScreen() { return <SimpleDataModule title="Templates" eyebrow="Reusable agency system" summary="Audit templates, first-90-day roadmap templates, task QA checklists, report sections and client-request templates reduce strategist setup time without flattening campaign strategy." cards={[{label:"Audit templates",value:"GBP · technical · on-page/CRO · competitors · citations · content · links · analytics"},{label:"Roadmap templates",value:"First 30 days · 90 days · 6 months · 12 months"},{label:"Approval model",value:"Templates can create drafts; human approval remains required for external strategy"}]} links={[['Start onboarding','/growth/campaigns/new'],['Open audits','/growth/audits']]} />; }
export function SettingsScreen() { return <SimpleDataModule title="Organization settings" eyebrow="Agency controls" summary="User roles, campaign assignment, notification preferences, audit trails and billing-ready organization settings live at the organization layer." cards={[{label:"Roles",value:"Agency Admin · Lead SEO · Strategist · Content/Outreach · Client Viewer · Client Editor"},{label:"Tenant protection",value:"Client access is scoped by organization + client ID through database RLS"},{label:"Auditability",value:"Sensitive changes can record actor, entity, before state, after state and metadata"}]} links={[['Open integrations','/growth/integrations'],['Demo login / roles','/growth/login']]} />; }

function SimpleDataModule({ title, eyebrow, summary, cards, links, extra }: { title: string; eyebrow: string; summary: string; cards: {label:string;value:string}[]; links: [string,string][]; extra?: React.ReactNode }) { return <Screen title={title} eyebrow={eyebrow} subtitle={summary}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cards.map((card) => <Card key={card.label} title={card.label}><p className="text-sm leading-6 text-slate-700">{card.value}</p></Card>)}</div>{extra}<div className="flex flex-wrap gap-2">{links.map(([label,href]) => <Link key={href} href={href} className={outlineButton}>{label}<ArrowRight className="h-4 w-4" /></Link>)}</div></Screen>; }
function ContentCard({ item }: { item: ContentItem }) { const campaign = demoCampaigns.find((row) => row.id === item.campaignId); return <Link href={`/growth/content/${item.id}`} className="rounded-2xl border border-[var(--border)] bg-white p-5 shadow-[var(--shadow-card)] transition hover:border-slate-300"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold uppercase text-slate-600">{item.type.replaceAll("_", " ")}</span><StatusBadge value={item.status} /></div><h2 className="mt-3 font-semibold leading-6 text-slate-950">{item.title}</h2><p className="mt-1 text-xs text-slate-500">{campaign?.clientName} · {item.location}</p><div className="mt-4 border-t border-[var(--border)] pt-3 text-xs text-slate-500">{item.clientAssetsRequired.length ? `${item.clientAssetsRequired.length} client asset dependencies` : "No client assets blocking"}{item.qaFlags.length ? <span className="ml-2 font-semibold text-amber-700">· {item.qaFlags.length} QA flag</span> : null}</div></Link>; }
function Screen({ title, eyebrow, subtitle, actions, children }: { title: string; eyebrow: string; subtitle: string; actions?: React.ReactNode; children: React.ReactNode }) { return <div className="space-y-6"><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-emerald-700">{eyebrow}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{subtitle}</p></div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</header>{children}</div>; }
function Card({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-[var(--border)] bg-white p-5 shadow-[var(--shadow-card)]"><h2 className="text-base font-semibold text-slate-900">{title}</h2>{subtitle && <p className="mt-1 text-xs leading-5 text-slate-500">{subtitle}</p>}<div className="mt-4">{children}</div></section>; }
function Stat({ label, value, tone }: { label: string; value: string; tone?: "amber"|"red"|"green" }) { return <div className={`rounded-xl border p-4 ${tone === "amber" ? "border-amber-200 bg-amber-50" : tone === "red" ? "border-red-200 bg-red-50" : tone === "green" ? "border-emerald-200 bg-emerald-50" : "border-[var(--border)] bg-white"}`}><div className={`text-xs ${tone === "amber" ? "text-amber-700" : tone === "red" ? "text-red-700" : tone === "green" ? "text-emerald-700" : "text-slate-500"}`}>{label}</div><div className="mt-1 text-xl font-semibold text-slate-950">{value}</div></div>; }
function Read({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-3"><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 text-sm font-medium leading-5 text-slate-800">{value}</div></div>; }
function ReportList({ title, rows, tone }: { title: string; rows: string[]; tone: "green"|"amber"|"blue" }) { const cls = tone === "green" ? "text-emerald-600" : tone === "amber" ? "text-amber-600" : "text-blue-600"; return <section><h3 className="text-sm font-semibold text-slate-900">{title}</h3><ul className="mt-2 space-y-2">{rows.map((row) => <li key={row} className="flex gap-2 text-sm leading-5 text-slate-600"><CheckCircle2 className={`mt-0.5 h-4 w-4 shrink-0 ${cls}`} />{row}</li>)}</ul></section>; }
function StatusBadge({ value }: { value: string }) { const normalized = value.toLowerCase(); const cls = normalized.includes("incorrect") || normalized.includes("blocked") || normalized.includes("error") || normalized.includes("rejected") ? "bg-red-50 text-red-700" : normalized.includes("wait") || normalized.includes("request") || normalized.includes("pending") || normalized.includes("draft") || normalized.includes("unavailable") ? "bg-amber-50 text-amber-700" : normalized.includes("connect") || normalized.includes("publish") || normalized.includes("claim") || normalized.includes("approve") || normalized.includes("complete") ? "bg-emerald-50 text-emerald-700" : "bg-blue-50 text-blue-700"; return <span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold capitalize ${cls}`}>{value.replaceAll("_", " ")}</span>; }
function Label({ children }: { children: React.ReactNode }) { return <span className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-slate-600">{children}</span>; }
function humanize(value: string) { return value.replace(/([A-Z])/g," $1").replaceAll("_"," ").replace(/^./,(letter)=>letter.toUpperCase()); }
function csvCell(value: string) { return `"${value.replaceAll('"','""')}"`; }
const fieldClass = "mt-1.5 h-10 w-full rounded-lg border border-[var(--border)] bg-white px-3 text-sm outline-none focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100";
const outlineButton = "inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-[var(--border)] bg-white px-3 text-sm font-semibold text-slate-700 hover:bg-slate-50";
const darkButton = "inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-slate-950 px-3 text-sm font-semibold text-white hover:bg-slate-800";
